example:
    property: HELLOWORLD
redis:
    port: 6379
    server: redis
signing:
    key: 345345fsdfsf5345
spring:
    database:
        driverClassName: org.postgresql.Driver
#    datasource:
#        password: '"{cipher}4788dfe1ccbe6485934aec2ffeddb06163ea3d616df5fd75be96aadd4df1da91"'
#        platform: '"postgres"'
#        testWhileIdle: '"true"'
#        url: '"jdbc:postgresql://database:5432/eagle_eye_local"'
#        username: '"postgres"'
#        validationQuery: '"SELECT 1"'
#    jpa:
#        database: '"POSTGRESQL"'
#        properties:
#            hibernate:
#                dialect: '"org.hibernate.dialect.PostgreSQLDialect"'
#        show-sql: '"true"'
